- name: ansible to install PyMySQL
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9
- name: create my sql server
  ansible.builtin.package:
    name: mysql-server
    state: present
- name: start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connect MySql 
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
  ignore_errors: true
  register: mysql_info

- name: print my sql info
  ansible.builtin.debug:
    msg: "{{ mysql_info }}"
- name: set up my sql
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
  when: mysql_info.failed is true